### PR TITLE
ADC control: map steer and speed to [-1000,1000] instead of [0,1000]

### PR DESCRIPTION
**Pull request by kervinck**
Otherwise the center of the pot meters aren't neutral for either steering or speed. This looks like a bug.

### CODE REVIEW

**Comment by Jan--Henrik** [comment]
Hey, 
Thanks for your contribution but that ain't a bug. We're shipping the stock firmware which everybody has to configure depending on the needs. For most projects we didn't use center zero potentiometers, however we should add a note on how to map the ADC accordingly.

**Comment by kervinck** [comment]
Allow me to explain, there are two (or 4...) issues with these two lines.

The first is that the ADC value is suggested to be mapped to a [-1000..1000] range with the CLAMP(x, -1000, 1000) macro. However, the notation is misleading, as negative values don't come out. The ADC value comes in as [0..4095], so CLAMP(x, 0, 1000) would be more appropriate.

This gives always non-negative values for 'cmd1' and 'cmd2', and from that, always non-negative values for 'steer' and 'speed'. Later these get converted to speedL and speedR. We can argue about the need for a negative overall speed of course, but only allowing steering into one direction and not the other... Yet that is what the code is doing. It can only steer in one direction.

The second issue is that the scaling with ADCx_MIN and ADCx_MAX is only correct for the case of ADCx_MIN == 0. Because the scaling is done with ADCx_MAX, and not with the range (ADCx_MAX - ADCx_MIN).

**Comment by kervinck** [comment]
Hi Jan Henrik. The scaling bug aside, would you care to comment on how to steer to the left under ADC control? I just can't wrap my head around it.

Given that 'cmd2' and 'steer' are always non-negative,

```
    speedR = CLAMP(speed * SPEED_COEFFICIENT -  steer * STEER_COEFFICIENT, -1000, 1000);
    speedL = CLAMP(speed * SPEED_COEFFICIENT +  steer * STEER_COEFFICIENT, -1000, 1000);
```

means that speedR can't exceed speedL at any time, no matter the hookup of potmeters?

**Comment by kervinck** [comment]
[For future reference:] Both issues are already addressed in this GitHub fork:
https://github.com/p-h-a-i-l/hoverboard-firmware-hack

**Pull request closed without merging**
